FROM centos:7

LABEL maintainer="krilor"

RUN yum -y erase vim-minimal iputils libss && \
    yum -y install openssh openssh-server openssh-clients && \
    yum -y clean all

RUN ssh-keygen -A

COPY sshd_config /etc/ssh/sshd_config
RUN passwd -d root

COPY run.sh /run.sh
RUN chmod +x /run.sh

EXPOSE 22
CMD ["/run.sh"]